# Generated by Django 2.2.24 on 2021-12-25 10:17

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0007_auto_20211220_1441"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 12, 27, 10, 17, 35, 726412, tzinfo=utc),
                verbose_name="актуальность ключа",
            ),
        ),
    ]
